### ISSUE TITLE
Add locale parameter (e.g. ?l=de_DE) to "Edit in CMS" button for working better with the fluent module

### ISSUE THREAD

**Issue by banglashi** [jonom/silverstripe-betternavigator#45]
Hi @jonom 
thanks for the great work. While implementing your module for a client the question arised if it would be possible to directly send the user to the CMS with the correct locale set when working in conjunction with the fluent module. It would need to append the locale to the url as an l parameter. I know it's currently using the $EditLink call in the template, but I am unsure if it makes sense to overload that method (could it have other implications?) or do a conditional in the template directly. Perhaps you have more insights or thoughts on this. Thanks.

**Comment by jonom** [comment]
Hi @banglashi you could try overloading `$EditLink`, I have a feeling that won't work though because that variable is passed in to the page object using `->customise()`, so I think that will probably take precedence over a method on the page. You could certainly provide your own method like `EditLinkWithLocale()` and override the template to swap that in.

I haven't used Fluent before but I'd be happy to review a PR to add support for this since it's the recommended translation module for Silverstripe. Maybe you could detect if Fluent is installed, and if it is then append the appropriate query string [here](https://github.com/jonom/silverstripe-betternavigator/blob/da6e75c1b12f31cd980b358367dd71bad9813e05/src/Extension/BetterNavigatorExtension.php#L109-L111) using [`Controller::join_links()`](https://api.silverstripe.org/4/SilverStripe/Control/Controller.html#method_join_links) which will take care of merging any url params.

**Comment by jonom** [comment]
Closing as inactive.
