### ISSUE TITLE
Includes JS even if not rendered

### ISSUE THREAD

**Issue by adrexia** [jonom/silverstripe-betternavigator#46]
`afterCallActionHandler`'s check of DBHTMLText means there are multiple reasons BetterNavigator might not be rendered, and the js still included.

**Comment by adrexia** [comment]
Oh! I think this is becasue some Controllers are returning ``$this``, rather than ``$this->render``. ``$this`` technically works, but breaks for this module.

**Comment by jonom** [comment]
Thanks for the report @adrexia. Hmmmmmmmmm 🤔 I haven't dived too deep in to this before, I didn't even know about the `CallActionHandler` hooks until @unclecheese had the idea to introduce them 😄. It looks like `Controller::handleAction()` should return either a `DBHTMLText` or `HTTPResponse`. So, Perhaps we should check for `$result instanceof DBHTMLText || $result instanceof HTTPResponse && strpos($result->getHeader('content-type'), 'text/html')) !== false`? We'll also have to make [`$html`](https://github.com/jonom/silverstripe-betternavigator/blob/master/src/Extension/BetterNavigatorExtension.php#L57) the result of either `$result->getValue()` or `$result->getBody()` accordingly.

I think that might fix the `$this` vs `$this->render()` discrepancy, which should make BetterNavigator render more often, but probably only solves part of the problem. An additional issue is that we're using different logic for the requirements to the html, and even if we only looked at `$this->shouldDisplay()`, the result of that could change between the execution of `beforeCallActionHandler()` and `afterCallActionHandler()`. We should try to consolidate that.

Maybe we should get rid of the `beforeCallActionHandler()` and manually write a script and css tag to the response body in the `afterCallActionHandler()` instead? That would ensure you get all or nothing (html + js + css) and de-fragment the logic. Potential drawback is that it would prevent people from blocking those resources through the `Requirements` API but I imagine that's not a common practice.

BTW @adrexia  v4 renders with a regular old `$BetterNavigator` variable instead of using these hoooks, and that was about the only significant change between v4 & v5, so feel free to revert to v4 for a (probably) easy fix.

**Comment by unclecheese** [comment]
Ugh. That `Requirements` API. Love those non-deterministic renders!

My preference would be to chuck the Javascript right into the HTML. That way you only get it when it renders. They should be colocated anyway, as they're all the same concern. I'd probably chuck the CSS in there, too. ;-)

**Comment by jonom** [comment]
We're of the same mind then. @adrexia I've pushed up a [branch](https://github.com/jonom/silverstripe-betternavigator/tree/fix-46) with a [fix](https://github.com/jonom/silverstripe-betternavigator/commit/5bbbcb591a5312395992a205fcc78a6feb536633), would you be able to test it and see if it resolves the issue for you?

**Comment by adrexia** [comment]
@jonom Sorry I missed this. I've just tested now and it seems to work well :)

**Comment by adrexia** [comment]
BUT the original cause of the bug probably does still need to be fixed. When used with the CWP Search Page controller, for example, index is a redirect.  So  `$result->setValue($html);` happens but throws a `Call to undefined method` error. 

I think perhaps the statusCode needs to be checked too? In this case the status is a 302 redirect.

**Comment by adrexia** [comment]
@jonom Actually, its easier than that even. It just needs to check if `$html` actually exists  

```
$html = $result instanceof DBHTMLText ? $result->getValue() : $result->getBody();

if (!$html) {
    return false;
}
```

^ adding that in fixes my errors

**Comment by jonom** [comment]
@adrexia thanks for your testing and feedback. Okay, that makes sense. My only concern is whether we need to return `null` or `$result` instead of `false`, because the `afterCallActionHandler` [looks unusual](https://github.com/silverstripe/silverstripe-framework/blob/237b2d5f74c20bb507a94a48f5c30a95c20525cf/src/Control/Controller.php#L300-L307) and seems to expect a result, and (news to me) non-null return values from extensions apparently [have meaning](https://github.com/silverstripe/silverstripe-framework/blob/237b2d5f74c20bb507a94a48f5c30a95c20525cf/src/Core/Extensible.php#L433-L436). I'm thinking this check and the earlier one should both return `null` (just `return;`).

@unclecheese maybe you're more familiar with the finer points of how the extension API works - any comments?

**Comment by adrexia** [comment]
Oh, maybe? It works currently, and we were already returning false before. Does it only have meaning if you are using php with strict typing? Or is it type checking for null somehow? 

https://github.com/silverstripe/silverstripe-framework/blob/237b2d5f74c20bb507a94a48f5c30a95c20525cf/src/Control/Controller.php#L303  that looks to be fine though? We would return false, and it would skip that part, and return result. The extend method looks a bit, but it wouldn't be the first time an extend has returned a false.

**Comment by jonom** [comment]
@adrexia Yeah I'm probably over-thinking it. We're not currently returning false though I think, looks like we're returning [`$result`](https://github.com/jonom/silverstripe-betternavigator/blob/master/src/Extension/BetterNavigatorExtension.php#L49-L55). It probably doesn't make a difference, but if you have time would you mind just testing whether returning `$result` and `null` both also work for you?
